# Site settings
author: Mark Guza
title: Leveling Up on my Coding Journey 
header-img: img/home-bg.png
email: guzamaguza@gmail.com
copyright_name: Mark Guza
description: > # this means to ignore newlines until "baseurl:"
  A blog about my coding journey through the Flatiron Program. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  guzamaguza

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
